package com.charbel.ecommerce.product.controller;

import java.util.List;
import java.util.UUID;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import com.charbel.ecommerce.product.dto.AddStockRequest;
import com.charbel.ecommerce.product.dto.AddStockResponse;
import com.charbel.ecommerce.product.dto.LowStockResponse;
import com.charbel.ecommerce.product.dto.ProductResponse;
import com.charbel.ecommerce.product.service.ProductService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@RestController
@RequestMapping("/api")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "Products", description = "Product management endpoints")
public class ProductController {

	private final ProductService productService;

	// Admin endpoints
	@PostMapping(value = "/admin/products", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
	@PreAuthorize("hasRole('ADMIN')")
	@Operation(summary = "Create a new product with AI-generated variants", 
			   description = "Creates a new product with color variants generated by AI from a single image. Admin only.", 
			   security = @SecurityRequirement(name = "bearerAuth"))
	public ResponseEntity<ProductResponse> createProduct(
			@RequestParam("image") MultipartFile image,
			@RequestParam("name") String name,
			@RequestParam("description") String description,
			@RequestParam("basePrice") Integer basePrice,
			@RequestParam("brandId") UUID brandId,
			@RequestParam("categoryId") UUID categoryId,
			@RequestParam("gender") String gender,
			@RequestParam("variants") String variantsJson,
			@RequestParam(value = "metadata", required = false) String metadataJson) {
		
		log.info("Admin creating new product with AI-generated variants: {}", name);
		
		try {
			ProductResponse response = productService.createProductWithAIVariants(
				image, name, description, basePrice, brandId, categoryId, gender, variantsJson, metadataJson);
			return ResponseEntity.status(HttpStatus.CREATED).body(response);
		} catch (Exception e) {
			log.error("Error creating product with AI variants", e);
			return ResponseEntity.internalServerError().build();
		}
	}

	@GetMapping("/admin/products/low-stock")
	@PreAuthorize("hasRole('ADMIN')")
	@Operation(summary = "Get low stock products", description = "Returns products with stock less than 5. Admin only.", security = @SecurityRequirement(name = "bearerAuth"))
	public ResponseEntity<List<LowStockResponse>> getLowStockProducts() {
		log.info("Admin requesting low stock products");
		List<LowStockResponse> response = productService.getLowStockProducts();
		return ResponseEntity.ok(response);
	}

	@GetMapping("/admin/products/low-stock-variants")
	@PreAuthorize("hasRole('ADMIN')")
	@Operation(summary = "Get low stock variants", description = "Returns product variants with stock less than 5. Admin only.", security = @SecurityRequirement(name = "bearerAuth"))
	public ResponseEntity<List<LowStockResponse>> getLowStockVariants() {
		log.info("Admin requesting low stock variants");
		List<LowStockResponse> response = productService.getLowStockVariants();
		return ResponseEntity.ok(response);
	}

	@PostMapping("/admin/products/add-stock")
	@PreAuthorize("hasRole('ADMIN')")
	@Operation(summary = "Add stock to variants", description = "Adds stock to multiple product variants. Admin only.", security = @SecurityRequirement(name = "bearerAuth"))
	public ResponseEntity<AddStockResponse> addStockToVariants(@Valid @RequestBody AddStockRequest request) {
		log.info("Admin adding stock to {} variants", request.getStockUpdates().size());
		AddStockResponse response = productService.addStockToVariants(request);
		return ResponseEntity.ok(response);
	}

	@PutMapping("/admin/products/{productId}/disable")
	@PreAuthorize("hasRole('ADMIN')")
	@Operation(summary = "Disable a product", description = "Sets product status to INACTIVE. Admin only.", security = @SecurityRequirement(name = "bearerAuth"))
	public ResponseEntity<ProductResponse> disableProduct(@PathVariable UUID productId) {
		log.info("Admin disabling product with ID: {}", productId);
		ProductResponse response = productService.disableProduct(productId);
		return ResponseEntity.ok(response);
	}

	// Public endpoints
	@GetMapping("/products")
	@Operation(summary = "Get paginated products", description = "Returns a paginated list of products with their variants")
	@SecurityRequirement(name = "bearerAuth")
	public ResponseEntity<Page<ProductResponse>> getProducts(@PageableDefault(size = 20) Pageable pageable) {
		log.info("Fetching products with pagination: page={}, size={}", pageable.getPageNumber(),
				pageable.getPageSize());
		Page<ProductResponse> response = productService.getProducts(pageable);
		return ResponseEntity.ok(response);
	}

	@GetMapping("/events/{eventId}/products")
	@Operation(summary = "Get products by event", description = "Returns a paginated list of products associated with a specific event")
	public ResponseEntity<Page<ProductResponse>> getProductsByEvent(@PathVariable UUID eventId,
			@PageableDefault(size = 20) Pageable pageable) {
		log.info("Fetching products for event ID: {} with pagination: page={}, size={}", eventId,
				pageable.getPageNumber(), pageable.getPageSize());
		Page<ProductResponse> response = productService.getProductsByEventId(eventId, pageable);
		return ResponseEntity.ok(response);
	}

	@GetMapping("/products/brand")
	@Operation(summary = "Get products by brand slug", description = "Returns a paginated list of products from a specific brand using brand slug")
	public ResponseEntity<Page<ProductResponse>> getProductsByBrandSlug(@RequestParam String brandSlug,
			@PageableDefault(size = 20) Pageable pageable) {
		log.info("Fetching products for brand slug: {} with pagination: page={}, size={}", brandSlug,
				pageable.getPageNumber(), pageable.getPageSize());
		Page<ProductResponse> response = productService.getProductsByBrandSlug(brandSlug, pageable);
		return ResponseEntity.ok(response);
	}

	@GetMapping("/products/category/{categoryId}")
	@Operation(summary = "Get products by category", description = "Returns a paginated list of products from a specific category")
	public ResponseEntity<Page<ProductResponse>> getProductsByCategory(@PathVariable UUID categoryId,
			@PageableDefault(size = 20) Pageable pageable) {
		log.info("Fetching products for category ID: {} with pagination: page={}, size={}", categoryId,
				pageable.getPageNumber(), pageable.getPageSize());
		Page<ProductResponse> response = productService.getProductsByCategoryId(categoryId, pageable);
		return ResponseEntity.ok(response);
	}

}
