name: Style Checks

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify (Spotless + Checkstyle)
        run: mvn -B -q --no-transfer-progress verify


